### ISSUE TITLE
rake generate_derivatives from archives folder

### ISSUE THREAD

**Issue by evanwill** [uidaholib/spec-lumber#6]
@dcnb check branch new-rake

this is just a quick tweak of the current Rakefile approach (rather than porting in the more complicated new version from Derek's sa_draft)

It has an "objects/archives" directory, where you would put your new scans. When you `rake generate_derivatives` it:

1. looks in "objects/archives" for .tif, .jpg, and .pdf (skips anything else) 
2. converts .tif into .jpg 
3. copies .jpg and .pdf into "objects" 
4. generates thumb in "objects/thumbs"
5. generates small in "objects/small"

Does this make sense?

Questions I have:

- folder structure: seems confusing to have "objects/archives" populate "objects". It would be easier from workflow perspective if the folder structure matched the structure on the webpages place where you have to copy them. Maybe it should be a different starting folder, like "media", then inside "media/archives", "media/objects", "media/objects/small", "media/objects/thumbs". ?
- filename normalize: it seems like it would be good to normalize filenames--particularly downcase everything, since there is a lot of `.JPG` vs `.jpg` which might end up causing hiccups on the server--but people would then also be aware of the normalizing, so that they use the correct references in the metadata/includes--which seems confusing too... 
- supported extensions: do we expand the supported extensions, right now only exactly `.tif`, `.jpg`, `.png` and `.pdf`. If it doesn't know how to generate derivatives, should it just copy the file over to "objects"? does `.tiff` need to be supported?
- PDF vs TIFF scanning workflow: in the workflow are they scanning to tif then creating a PDF from them? Would the page tifs be added to the archives folder or just the pdf? This task can't tell that say a bunch of tifs that are the components of a PDF should be ignored, so I guess how you want to handle that needs to be built into the workflow.

**Comment by dcnb** [comment]
- folder structure: seems confusing to have "objects/archives" populate
   "objects". It would be easier from workflow perspective if the folder
   structure matched the structure on the webpages place where you have to
   copy them. Maybe it should be a different starting folder, like "media",
   then inside "media/archives", "media/objects", "media/objects/small",
   "media/objects/thumbs". ?
      - I think it should be objects/archives -- then they can just grab
      the archives, small, thumb folders and the new file in the objects
      directory all at once and drag into webpages.
   - filename normalize: it seems like it would be good to normalize
   filenames--particularly downcase everything, since there is a lot of .JPG
    vs .jpg which might end up causing hiccups on the server--but people
   would then also be aware of the normalizing, so that they use the correct
   references in the metadata/includes--which seems confusing too...
      - Would be good. And really, this should work better if the archives
      directory is where we start --> all the files on the website will be
      downcased -- and everyone needs to be better about this anyway ...
   - supported extensions: do we expand the supported extensions, right now
   only exactly .tif, .jpg, .png and .pdf. If it doesn't know how to
   generate derivatives, should it just copy the file over to "objects"? does
   .tiff need to be supported?
      - I thought it was .tiff? I think whatever we tell them should be
      fine. Had a question about png files, so I think that's good.
   - PDF vs TIFF scanning workflow: in the workflow are they scanning to
   tif then creating a PDF from them? Would the page tifs be added to the
   archives folder or just the pdf? This task can't tell that say a bunch of
   tifs that are the components of a PDF should be ignored, so I guess how you
   want to handle that needs to be built into the workflow.
      - I think I'd want them to just create a pdf. There are very few PDFs
      currently so let's not worry to much about that.

—

**Comment by evanwill** [comment]
done and documented in Wiki
